# Generated by Django 5.0.3 on 2024-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtext_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='get_arguments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
